# Generated by Django 2.1.7 on 2019-04-23 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('posttitle', models.CharField(max_length=100)),
                ('postimage', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=50)),
                ('activity', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=10)),
                ('emailid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('dobd', models.CharField(max_length=2)),
                ('dobm', models.CharField(max_length=5)),
                ('doby', models.CharField(max_length=4)),
                ('gender', models.CharField(max_length=6)),
                ('displayimage', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.signup'),
        ),
        migrations.AddField(
            model_name='like',
            name='postid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.post'),
        ),
        migrations.AddField(
            model_name='like',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.signup'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('postid', 'userid')},
        ),
    ]
