# Generated by Django 2.1.7 on 2019-04-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.AlterField(
            model_name='login',
            name='emailid',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
