# Generated by Django 2.1.7 on 2019-04-27 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_friendslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendslist',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='app1.signup'),
        ),
        migrations.AlterField(
            model_name='friendslist',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='app1.signup'),
        ),
    ]
