# Generated by Django 2.1.7 on 2019-08-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='commenttext',
        ),
    ]
